package StockMarket;


/**
* StockMarket/StockSymbolListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StockMarket.idl
* Segunda-feira, 26 de Junho de 2017 13h17min25s BRT
*/


// Um StockSymbolList é uma sequência de StockSymbols.
public final class StockSymbolListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public StockSymbolListHolder ()
  {
  }

  public StockSymbolListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StockMarket.StockSymbolListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StockMarket.StockSymbolListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StockMarket.StockSymbolListHelper.type ();
  }

}
