package StockMarket;


/**
* StockMarket/StockInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StockMarket.idl
* Segunda-feira, 26 de Junho de 2017 16h14min10s BRT
*/

public abstract class StockInfo implements org.omg.CORBA.portable.StreamableValue
{
  public String name = null;
  public float value = (float)0;

  private static String[] _truncatable_ids = {
    StockMarket.StockInfoHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public abstract String _toString ();

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    this.name = istream.read_string ();
    this.value = istream.read_float ();
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    ostream.write_string (this.name);
    ostream.write_float (this.value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StockMarket.StockInfoHelper.type ();
  }
} // class StockInfo
