package StockMarket;


/**
* StockMarket/UnknownSymbol.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StockMarket.idl
* Segunda-feira, 26 de Junho de 2017 16h14min09s BRT
*/

public final class UnknownSymbol extends org.omg.CORBA.UserException
{
  public String symbol = null;

  public UnknownSymbol ()
  {
    super(UnknownSymbolHelper.id());
  } // ctor

  public UnknownSymbol (String _symbol)
  {
    super(UnknownSymbolHelper.id());
    symbol = _symbol;
  } // ctor


  public UnknownSymbol (String $reason, String _symbol)
  {
    super(UnknownSymbolHelper.id() + "  " + $reason);
    symbol = _symbol;
  } // ctor

} // class UnknownSymbol
